language: node_js
node_js:
  - v13.9.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn lint
  - yarn test --coverage
  - yarn build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_6e5e35a70d3f_key -iv $encrypted_6e5e35a70d3f_iv
    -in .travis-deploy-key.enc -out .travis-deploy-key -d
deploy:
  provider: pages:git
  deploy_key: .travis-deploy-key
  local_dir: build
  edge: true
  on:
    branch: master
